name: lint

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    name: Run tox with ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Install tox
        run: uv sync --only-group tox --frozen --python 3.13
      - name: Run tox for python ${{ matrix.python-version }}
        run: uv run tox -e py${{ matrix.python-version }}
